version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microting.eForm
    versions:
    - 4.3.14
    - 4.3.17
    - 4.3.18
    - 4.3.9
    - 4.4.1
    - 4.4.13
    - 4.4.14
    - 4.4.17
    - 4.4.19
    - 4.4.20
    - 4.4.22
    - 4.4.24
    - 4.4.26
    - 4.4.27
    - 4.4.31
    - 4.4.36
    - 4.4.6
    - 4.4.7
    - 4.5.2
  - dependency-name: Microting.eFormApi.BasePn
    versions:
    - 2.0.101
    - 2.0.102
    - 2.0.103
    - 2.0.107
    - 2.0.108
    - 2.0.110
    - 2.0.111
    - 2.0.112
    - 2.0.113
    - 2.0.116
    - 2.0.117
    - 2.0.118
    - 2.0.122
    - 2.0.127
    - 2.0.88
    - 2.0.97
    - 2.1.2
  - dependency-name: Microting.WorkOrderBase
    versions:
    - 1.2.11
    - 1.2.20
    - 1.2.24
    - 1.2.25
    - 1.2.29
    - 1.2.31
    - 1.2.32
    - 1.2.33
    - 1.2.34
    - 1.2.36
    - 1.2.37
    - 1.2.38
    - 1.2.40
    - 1.2.44
  - dependency-name: Microsoft.EntityFrameworkCore.Proxies
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
